import React from 'react';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import { Link } from 'react-router-dom';

const StockModule1= () => {



  const cardData = [
    {
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSN9c8t2Isl78AkqHtVkYQGl9Hw5Ig6NLLTQw&s",
      title: "1. The Need to Invest",
      description:"Learn about the importance of savings. Identify avenues to invest the savings in suitable investment vehicle. Compare historical returns generated by different assets, and know what to expect from you .."
    },
    {
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDmYZBEX2iARBTlIUEO_yzAD6PvWsGs1YVGg&s",
      title: "2. Regulators, the guardians of capital markets",
      description: "Find out who and how the regulators govern the financial markets and also understand different types of financial market participants. Understand the need to regulate the markets. .."
    },
    {
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpx4n_SRuLaA_6oYLqjJ2jprVuJCx4YbifnMUA6sCDY9OhqsFdBnZ5zyvbt5z0PopVxdI&usqp=CAU",
      title: "3. Market Intermediaries",
      description: "An overview of the financial intermediaries in the Indian stock market and the services they offer. .."
    },
    {
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTw-9rPmzSNNpe4ARLP72WnLYFEi0MA2qe-D4FoHBZC15a4r0xlC89I-mCzhodV2q3wlI&usqp=CAU",
      title: "4. The IPO Markets (Part 1)",
      description: "Understand the origins of business and the funding environment of business. Learn about the different funding stages and also learn how funding works. .."
    },
    {
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIfS-6a5f7LYBNaSQwX07erBWQH-XIbjjGL01f0wfPBu1RbRvwPJh_Yw5GbzxLknw6SGk&usqp=CAU",
      title: "5. The IPO Markets (Part 2)",
      description: "Learn the basics of the IPO market and the process of how to go about investing in IPO’s. This chapter also helps us understand the different IPO Jargons that are commonly used. .."
    },
    {
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCGh0m__c3e2B6ItZjwJCf7WI_SJUJi6-fnA&s",
      title: "6. The Stock Markets",
      description: "We explore the basics of stock trading and understand what makes the stock move on a minute by minute basis. We also explore concept of return calculation. .."
    },
    {
      image: "https://bsmedia.business-standard.com/_media/bs/img/article/2022-10/31/full/1667238624-3634.jpg?im=FitAndFill=(382,233)",
      title: "7. The Stock Markets Index",
      description: "An overview of the Indian Stock Market Indices, their construction, and practical uses in trading .."
    },
    {
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEGA0VaQHlOpgqCSi_gbN6eq3QDgRcApln1FELwrDyBM4_BxXG5xZkd0Yw7arUg5xGnHY&usqp=CAU",
      title: "8. Commonly Used Jargons",
      description: "Glossary of common stock market terms & associated concepts used in trading. We also explain in detail on how to short a stock. .."
    },
    {
      image: "https://images.pexels.com/photos/6770611/pexels-photo-6770611.jpeg?auto=compress&cs=tinysrgb&w=400",
      title: "9. The Trading Terminal",
      description: "An introduction to The Trading Terminal, its interface, various functionalities and relevant concepts .."
    },
    {
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1r88BQVvNyy5n-zwyia-Ypwxz5JFNn1r6eQ&s",
      title: "10. Clearing and Settlement Process",
      description: "The behind the scene operations involved in share buying & selling .."
    }
  ];

  return (
    <div className='living'>

    <div className="projects-container">
      <div className="cards-container">
        {cardData.map((card, index) => (
                <Card
                key={index}
                className="card"
                sx={{
                    backgroundColor: '#f9f9f9',
                    border: '1px solid #ddd',
                    borderRadius: '8px',
                    padding: '20px',
                    width: '30%',
                    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
                    transition: 'transform 0.2s',
                    '&:hover': {
                        transform: 'scale(1.05)',
                    },
                }}
                >
                <CardMedia
                  sx={{ height: 180 }}
                  image={card.image}
                  title={card.title}
                  
                  />
                <CardContent>
                  <Typography fontFamily={'serif'} variant='h5'>{card.title}</Typography>
                  <Typography variant="body2" color="text.secondary">
                    {card.description}
                  </Typography>
                </CardContent>
                <CardActions>
                 
                </CardActions>
                <div className='leo'>
        
                 <Link to="/chapter1" >
               <Button  >
                 <b style={{color:"#9b59b6",fontSize:"15px"}} >
                  view Chapter
                  </b>
               </Button>
                 </Link>
               &emsp;&emsp;&emsp;&emsp;
                
                </div>
        
              </Card>
        ))}
      </div>
   </div>
   </div>
  );
};

const modalStyle = {
  position:'absolute',
  top: '50%',
  left: '50%',
  transform: 'translate(-50%, -50%)',
  width: '80%',
  height: '80%',
  bgcolor: 'background.paper',
  boxShadow: 24,
  p: 4,
  outline: 'none',
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
};

export default StockModule1 ;